# Generated by Django 5.0.1 on 2024-02-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='college_id',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='AIDS', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(default='SY', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='dead_kt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='pranav.narkhede@somaiya.edu', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='live_kt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=7620260232, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='practical_batch',
            field=models.CharField(default='S', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='proctor_batch',
            field=models.CharField(default='S', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.IntegerField(default=41),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_admission',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
