# Generated by Django 5.0.1 on 2024-02-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPP', '0002_rename_student_id_student_college_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='pranav', upload_to='student_images/'),
            preserve_default=False,
        ),
    ]
