# Generated by Django 5.0.1 on 2024-02-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPP', '0003_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcements', models.CharField(max_length=200)),
            ],
        ),
    ]
