# Generated by Django 5.0.1 on 2024-03-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPP', '0010_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='student',
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_images/'),
        ),
    ]
